Rate limiter to deposit call
availproject/faucet-bot pull request #1
Opened 2023-05-08 19:16 UTC by kroos47

- Added rate limit to deposit call
- Added a submodule for avail-js wrapper(for now)

2023-05-09 08:55 UTC, prabal-banerjee approved these changes

2023-05-10 19:40 UTC, vthunder requested changes
Approved with noted changes - in particular not leaving around unused code (src/avail.js) is important.

2023-05-10 19:40 UTC, vthunder commented on .gitmodules
If you're switching to this api, please fully remove src/avail.js so it doesn't end up as cruft here.

2023-05-10 19:40 UTC, vthunder commented on src/app.js
> +      const cooldownAmount = 3 * 60 * 1000;
This is 3 minutes, right? Can you add a comment like "// 3 minutes" for clarity?

2023-05-10 19:40 UTC, vthunder commented on src/commands.js
> +        content: `There was a problem transferring. Kindly report to the Avail Team.`,
More grammatical: "There was a problem with the transfer. Kindly report to the Avail Team."

2023-05-16 12:12 UTC, merged